name: example
description: "A new Flutter project."
publish_to: 'none'
resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.2
  fluent_ui_settings: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
