name: fluent_ui_settings
description: "Reusable Fluent UI extension widgets to quickly build stunning, Windows-native-like settings pages"
repository: https://github.com/lisproj/fluent-ui-extends
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
