name: fluent_ui_settings
description: "A new Flutter package project."
repository: https://github.com/lisproj/fluent-ui-extends
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
